// CodePanel.tsx
/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import { useEffect, useRef, useState } from "react";
import {
  SandpackProvider,
  SandpackLayout,
  SandpackCodeEditor,
  SandpackPreview,
  SandpackFileExplorer,
  SandpackConsole,
  useSandpack,
  useErrorMessage,
} from "@codesandbox/sandpack-react";
import {
  dracula,
  nightOwl,
  atomDark,
  cyberpunk,
  monokaiPro,
  githubLight,
} from "@codesandbox/sandpack-themes";
import {
  Eye,
  Code2,
  Terminal,
  Palette,
  Download,
  AlertTriangle,
  Bot,
  Loader2,
  ArrowUp,
  X,
} from "lucide-react";
import { RingLoader } from "react-spinners";
import JSZip from "jszip";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { exportWorkspace } from "@/actions/workspace";
import type { FileData, StatusStep } from "@/types/workspace";

// ─── Placeholder ──────────────────────────────────────────────────────────────

const PLACEHOLDER_FILES = {
  "/App.js": {
    code: `export default function App() {
  return (
    <div style={{
      minHeight: "100vh",
      background: "#0a0a0a",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontFamily: "system-ui, sans-serif",
    }}>
      <div style={{ textAlign: "center", color: "rgba(255,255,255,0.3)" }}>
        <div style={{ fontSize: 40, marginBottom: 16 }}>⚡</div>
        <p style={{ fontSize: 14 }}>Your app will appear here</p>
      </div>
    </div>
  );
}`,
  },
};

// ─── Pinned versions for fast CodeSandbox CDN caching ─────────────────────────

const KNOWN_DEPENDENCIES: Record<string, string> = {
  "lucide-react": "^1.16.0",
  "react-router-dom": "^6.28.0",
  recharts: "^2.15.0",
  clsx: "^2.1.1",
  "tailwind-merge": "^3.0.0",
  "class-variance-authority": "^0.7.1",
  "framer-motion": "^11.15.0",
  motion: "^11.15.0",
  "date-fns": "^4.1.0",
  "canvas-confetti": "^1.9.4",
  axios: "^1.7.9",
  zod: "^3.24.1",
  "react-hook-form": "^7.54.2",
  "@hookform/resolvers": "^3.9.1",
  "@radix-ui/react-dialog": "^1.1.4",
  "@radix-ui/react-dropdown-menu": "^2.1.4",
  "@radix-ui/react-tabs": "^1.1.2",
  "@radix-ui/react-tooltip": "^1.1.6",
  "@radix-ui/react-accordion": "^1.2.2",
  "@radix-ui/react-select": "^2.1.4",
};

/**
 * Resolves only the dependencies that this specific app actually requires.
 * Prevents Sandpack from timing out by avoiding downloading 20+ heavy unused packages.
 */
function resolveAppDependencies(fileData: FileData | null): Record<string, string> {
  const deps: Record<string, string> = {
    "lucide-react": "^1.16.0",
  };

  // 1. Include explicit dependencies generated by AI, normalizing "latest" to cached pinned versions
  if (fileData?.dependencies) {
    for (const [pkg, ver] of Object.entries(fileData.dependencies)) {
      if (ver && ver !== "latest") {
        deps[pkg] = ver;
      } else {
        deps[pkg] = KNOWN_DEPENDENCIES[pkg] || "^1.0.0";
      }
    }
  }

  // 2. Scan file source code for any imported packages
  if (fileData?.files) {
    const allCode = Object.values(fileData.files)
      .map((f) => (typeof f === "object" && f && "code" in f ? f.code : ""))
      .join("\n");

    for (const [pkg, ver] of Object.entries(KNOWN_DEPENDENCIES)) {
      if (!deps[pkg]) {
        const escaped = pkg.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&");
        if (new RegExp(`from\\s+['"]${escaped}(?:/.*)?['"]`, "m").test(allCode)) {
          deps[pkg] = ver;
        }
      }
    }
  }

  return deps;
}

// ─── Themes ───────────────────────────────────────────────────────────────────

export const FORGE_DARK_THEME = {
  colors: {
    surface1: "#0a0a0a",
    surface2: "#121215",
    surface3: "#1a1a22",
    clickable: "#94a3b8",
    base: "#f8fafc",
    disabled: "#475569",
    hover: "#ffffff",
    accent: "#8b5cf6",
    error: "#f87171",
    errorSurface: "#450a0a",
    warning: "#fbbf24",
    warningSurface: "#451a03",
  },
  syntax: {
    plain: "#f8fafc",
    comment: {
      color: "#64748b",
      fontStyle: "italic" as const,
    },
    keyword: "#c084fc",
    tag: "#38bdf8",
    punctuation: "#94a3b8",
    definition: "#f472b6",
    property: "#67e8f9",
    static: "#fb923c",
    string: "#4ade80",
  },
  font: {
    body: 'var(--font-geist-sans), -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    mono: 'var(--font-geist-mono), "Fira Code", "JetBrains Mono", Menlo, Consolas, monospace',
    size: "13px",
    lineHeight: "22px",
  },
};

export const AVAILABLE_THEMES = {
  forgeDark: { name: "Forge Dark", theme: FORGE_DARK_THEME },
  dracula: { name: "Dracula", theme: dracula },
  nightOwl: { name: "Night Owl", theme: nightOwl },
  atomDark: { name: "Atom Dark", theme: atomDark },
  cyberpunk: { name: "Cyberpunk", theme: cyberpunk },
  monokaiPro: { name: "Monokai Pro", theme: monokaiPro },
  githubLight: { name: "GitHub Light", theme: githubLight },
} as const;

export type ThemeKey = keyof typeof AVAILABLE_THEMES;

// ─── Types ────────────────────────────────────────────────────────────────────

type ActiveTab = "preview" | "code" | "console";

interface CodePanelProps {
  fileData: FileData | null;
  isGenerating: boolean;
  statusLog: StatusStep[];
  onImprove: (userRequest: string) => Promise<void>;
  onFixError: (error: string) => Promise<void>;
  onFilePatch: (patches: FileData) => void;
  appTitle: string | null;
  isImproving: boolean;
  workspaceId: string | null;
  userId: string;
}

// ─── SandpackInner ────────────────────────────────────────────────────────────
// Lives inside SandpackProvider so it can call useSandpack().
// Receives fileData as a prop and uses updateFile() to push code changes
// into the live Sandpack instance without remounting the provider.

function SandpackInner({
  isGenerating,
  statusLog,
  activeTab,
  setActiveTab,
  themeKey,
  onThemeChange,
  onImprove,
  onFixError,
  fileData,
  appTitle,
  isImproving,
  workspaceId,
  userId,
}: {
  isGenerating: boolean;
  statusLog: StatusStep[];
  activeTab: ActiveTab;
  setActiveTab: (t: ActiveTab) => void;
  themeKey: ThemeKey;
  onThemeChange: (key: ThemeKey) => void;
  onImprove: (userRequest: string) => Promise<void>;
  onFixError: (error: string) => Promise<void>;
  fileData: FileData | null;
  appTitle: string | null;
  isImproving: boolean;
  workspaceId: string | null;
  userId: string;
}) {
  const { sandpack, listen } = useSandpack();
  const sandpackErrorMessage = useErrorMessage();
  const [previewError, setPreviewError] = useState<string | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [isExportingWorkspace, setIsExportingWorkspace] = useState(false);
  const [improveInput, setImproveInput] = useState("");
  const [showImproveInput, setShowImproveInput] = useState(false);
  const unsubscribeRef = useRef<(() => void) | null>(null);

  // Sync bundler/syntax errors reported by useErrorMessage hook
  useEffect(() => {
    if (sandpackErrorMessage) {
      setPreviewError(sandpackErrorMessage);
    }
  }, [sandpackErrorMessage]);

  // Push file content updates into Sandpack without remounting.
  // Uses atomic batch update (passing an object) instead of looping one by one,
  // preventing multiple cascading bundler restarts.
  const prevFilesRef = useRef<Record<string, { code: string }>>({});
  useEffect(() => {
    if (!fileData?.files) return;
    const prev = prevFilesRef.current;
    const changedFiles: Record<string, string> = {};
    let hasChanges = false;

    for (const [path, { code }] of Object.entries(fileData.files)) {
      if (prev[path]?.code !== code) {
        changedFiles[path] = code;
        hasChanges = true;
      }
    }

    if (hasChanges) {
      sandpack.updateFile(changedFiles);
    }
    prevFilesRef.current = fileData.files;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fileData?.files]);

  // Grant Permissions-Policy 'unload *' to all Sandpack iframes to resolve Chromium unload violations
  useEffect(() => {
    const applyPermissions = (iframe: HTMLIFrameElement) => {
      const currentAllow = iframe.getAttribute("allow") || "";
      if (!currentAllow.includes("unload")) {
        iframe.setAttribute(
          "allow",
          `${currentAllow ? currentAllow + "; " : ""}unload *; accelerometer; camera; encrypted-media; geolocation; gyroscope; microphone; midi; clipboard-write;`
        );
      }
    };

    // Scan existing iframes
    document.querySelectorAll<HTMLIFrameElement>("iframe").forEach(applyPermissions);

    // Watch for dynamically inserted Sandpack bundler and preview iframes
    const observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        mutation.addedNodes.forEach((node) => {
          if (node instanceof HTMLIFrameElement) {
            applyPermissions(node);
          } else if (node instanceof HTMLElement) {
            node.querySelectorAll<HTMLIFrameElement>("iframe").forEach(applyPermissions);
          }
        });
      }
    });

    observer.observe(document.body, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, []);

  // Listen for Sandpack runtime errors
  useEffect(() => {
    unsubscribeRef.current = listen((msg) => {
      if (
        msg.type === "action" &&
        "action" in msg &&
        msg.action === "show-error"
      ) {
        const errMsg =
          "message" in msg && typeof msg.message === "string"
            ? msg.message
            : "An error occurred in the preview.";
        setPreviewError(errMsg);
        return;
      }
      if (msg.type === "compile" && "message" in msg && typeof msg.message === "string" && msg.message) {
        setPreviewError(msg.message);
        return;
      }
      if (msg.type === "success") {
        setPreviewError(null);
      }
    });
    return () => unsubscribeRef.current?.();
  }, [listen]);

  useEffect(() => {
    if (isGenerating) setPreviewError(null);
  }, [isGenerating]);

  const handleImproveSubmit = async () => {
    const trimmed = improveInput.trim();
    if (!trimmed || isImproving) return;
    setImproveInput("");
    setShowImproveInput(false);
    await onImprove(trimmed);
  };

  // ── Export to ZIP ──────────────────────────────────────────────────────────
  const handleExportZip = async () => {
    if (isExporting) return;
    setIsExporting(true);
    try {
      const filesToZip =
        Object.keys(sandpack.files).length > 0
          ? sandpack.files
          : fileData?.files ?? {};

      const dependencies = resolveAppDependencies(fileData);

      const zip = new JSZip();

      const packageJson = {
        name: "forge-app",
        version: "1.0.0",
        private: true,
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          "react-scripts": "5.0.1",
          ...dependencies,
        },
        scripts: {
          start: "react-scripts start",
          build: "react-scripts build",
        },
        browserslist: {
          production: [">0.2%", "not dead", "not op_mini all"],
          development: ["last 1 chrome version"],
        },
      };
      zip.file("package.json", JSON.stringify(packageJson, null, 2));

      zip.file(
        "public/index.html",
        `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Forge App</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>`
      );

      for (const [filePath, fileObj] of Object.entries(filesToZip)) {
        const code =
          typeof fileObj === "object" && fileObj !== null && "code" in fileObj
            ? (fileObj as { code: string }).code
            : "";
        const zipPath = filePath.startsWith("/")
          ? `src${filePath}`
          : `src/${filePath}`;
        zip.file(zipPath, code);
      }

      zip.file(
        "src/index.js",
        `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<React.StrictMode><App /></React.StrictMode>);`
      );

      zip.file(
        "README.md",
        `# Forge App\n\nGenerated with [Forge](https://forge.app).\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\``
      );

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      const zipName = appTitle
        ? `${appTitle
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/^-|-$/g, "")}.zip`
        : "forge-app.zip";
      a.download = zipName;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Export failed:", err);
    } finally {
      setIsExporting(false);
    }
  };

  // ── Export workspace as JSON ───────────────────────────────────────────────
  const handleExportWorkspace = async () => {
    if (isExportingWorkspace || !workspaceId) return;
    setIsExportingWorkspace(true);
    try {
      const data = await exportWorkspace(workspaceId, userId);
      if (!data) return;

      const blob = new Blob([JSON.stringify(data, null, 2)], {
        type: "application/json",
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      const slug = appTitle
        ? appTitle
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/^-|-$/g, "")
        : "forge-app";
      a.download = `${slug}-workspace.json`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Workspace export failed:", err);
    } finally {
      setIsExportingWorkspace(false);
    }
  };

  const currentStepLabel =
    statusLog[statusLog.length - 1]?.label ?? "Generating…";

  return (
    <Tabs
      value={activeTab}
      onValueChange={(v) => setActiveTab(v as ActiveTab)}
      className="flex h-full w-full flex-1 flex-col gap-0 min-h-0 overflow-hidden"
    >
      {/* Tabs + Actions bar */}
      <div className="flex items-center justify-between border-b border-white/6 px-2 shrink-0">
        <TabsList
          variant="line"
          className="h-auto gap-0 rounded-none bg-transparent p-0"
        >
          <TabsTrigger className="border-b-2 pt-2" value="preview">
            <Eye className="h-3.5 w-3.5" />
            Preview
          </TabsTrigger>
          <TabsTrigger className="border-b-2 pt-2" value="code">
            <Code2 className="h-3.5 w-3.5" />
            Code
          </TabsTrigger>
          <TabsTrigger className="border-b-2 pt-2" value="console">
            <Terminal className="h-3.5 w-3.5" />
            Console
          </TabsTrigger>
        </TabsList>

        <div className="flex items-center gap-1.5">
          {/* ── Theme Selector ── */}
          <div className="flex items-center gap-1.5 rounded-md border border-white/8 bg-white/[0.03] px-2 py-0.5 text-xs text-white/50 transition-colors hover:border-white/15">
            <Palette className="h-3.5 w-3.5 text-violet-400 shrink-0" />
            <select
              value={themeKey}
              onChange={(e) => onThemeChange(e.target.value as ThemeKey)}
              aria-label="Editor theme"
              className="h-6 cursor-pointer bg-transparent text-[11px] font-medium text-white/70 focus:outline-none"
            >
              {Object.entries(AVAILABLE_THEMES).map(([key, item]) => (
                <option
                  key={key}
                  value={key}
                  className="bg-[#121215] text-white/90"
                >
                  {item.name}
                </option>
              ))}
            </select>
          </div>

          {/* ── Improve button ── */}
          {showImproveInput ? (
            <div className="flex items-center gap-1.5">
              <div className="relative flex items-center">
                <Bot className="pointer-events-none absolute left-2.5 h-3.5 w-3.5 text-violet-400" />
                <input
                  autoFocus
                  value={improveInput}
                  onChange={(e) => setImproveInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") handleImproveSubmit();
                    if (e.key === "Escape") setShowImproveInput(false);
                  }}
                  placeholder="What should I improve?"
                  className="h-7 w-56 rounded-md border border-violet-500/30 bg-gradient-to-r from-violet-500/10 via-fuchsia-500/10 to-cyan-500/10 pl-8 pr-3 text-xs text-white/80 placeholder:text-white/30 focus:border-violet-400/50 focus:outline-none focus:shadow-[0_0_10px_rgba(139,92,246,0.2)]"
                />
              </div>
              <button
                onClick={handleImproveSubmit}
                disabled={!improveInput.trim() || isImproving}
                className="group relative flex h-7 w-7 items-center justify-center overflow-hidden rounded-md border border-violet-500/30 bg-gradient-to-br from-violet-500/20 to-fuchsia-500/20 text-violet-300 transition-all duration-200 hover:border-violet-400/50 hover:from-violet-500/30 hover:to-fuchsia-500/30 hover:shadow-[0_0_10px_rgba(139,92,246,0.3)] disabled:cursor-not-allowed disabled:opacity-40"
              >
                {isImproving ? (
                  <Loader2 className="h-3 w-3 animate-spin" />
                ) : (
                  <ArrowUp className="h-3 w-3" />
                )}
              </button>
            </div>
          ) : (
            <button
              onClick={() => setShowImproveInput(true)}
              disabled={isImproving || !fileData}
              className="group relative flex h-7 cursor-pointer items-center gap-1.5 overflow-hidden rounded-md border border-white/10 bg-gradient-to-r from-violet-500/10 via-fuchsia-500/10 to-cyan-500/10 px-2.5 text-xs font-medium transition-all duration-300 hover:border-white/20 hover:from-violet-500/20 hover:via-fuchsia-500/20 hover:to-cyan-500/20 hover:shadow-[0_0_12px_rgba(139,92,246,0.3)] disabled:cursor-not-allowed disabled:opacity-40"
            >
              <span className="pointer-events-none absolute inset-0 -translate-x-full animate-[shimmer_2.5s_infinite] bg-gradient-to-r from-transparent via-white/10 to-transparent" />
              {isImproving ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin text-violet-400" />
              ) : (
                <Bot className="h-3.5 w-3.5 text-violet-400 transition-colors group-hover:text-violet-300" />
              )}
              <span className="bg-gradient-to-r from-violet-300 via-fuchsia-300 to-cyan-300 bg-clip-text text-transparent">
                {isImproving ? "Improving…" : "Improve with Agent"}
              </span>
            </button>
          )}

          <Button
            variant="ghost"
            onClick={handleExportZip}
            disabled={isExporting || !fileData}
            className="cursor-pointer text-white/60 hover:text-white/90"
          >
            {isExporting ? (
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
            ) : (
              <Download className="h-3.5 w-3.5" />
            )}
            Download ZIP
          </Button>

          <Button
            variant="ghost"
            onClick={handleExportWorkspace}
            disabled={isExportingWorkspace || !workspaceId}
            className="cursor-pointer text-white/60 hover:text-white/90"
          >
            {isExportingWorkspace ? (
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
            ) : (
              <Download className="h-3.5 w-3.5" />
            )}
            Export Workspace
          </Button>
        </div>
      </div>

      {/* Content area */}
      <div className="relative flex-1 w-full h-full min-h-0 overflow-hidden flex flex-col">
        {(isGenerating || isImproving) && (
          <div className="absolute inset-0 z-20 flex flex-col items-center justify-center gap-6 bg-[#0a0a0a]/85 backdrop-blur-sm">
            <RingLoader color="#60a5fa" size={64} speedMultiplier={0.8} />
            <div className="flex flex-col items-center gap-1.5">
              <p className="text-sm font-medium text-white/60">
                {isImproving ? "Improving with Cline AI…" : currentStepLabel}
              </p>
              <p className="text-xs text-white/20">
                This usually takes 10–20 seconds
              </p>
            </div>
          </div>
        )}

        <TabsContent
          value="preview"
          keepMounted
          className="m-0 h-full w-full flex-1 flex flex-col min-h-0 [&[hidden]]:!hidden data-[state=inactive]:!hidden data-[hidden]:!hidden"
        >
          <SandpackLayout
            style={{
              height: "100%",
              width: "100%",
              border: "none",
              borderRadius: 0,
              background: "transparent",
              display: "flex",
              flexDirection: "column",
              flex: 1,
              minHeight: 0,
            }}
          >
            <SandpackPreview
              style={{ height: "100%", width: "100%", flex: 1, minHeight: 0 }}
              className="h-full w-full flex-1 min-h-0"
              showOpenInCodeSandbox={false}
              showRefreshButton={true}
              showRestartButton={true}
              showOpenNewtab={true}
            />
          </SandpackLayout>
        </TabsContent>

        <TabsContent
          value="code"
          keepMounted
          className="m-0 h-full w-full flex-1 flex flex-col min-h-0 [&[hidden]]:!hidden data-[state=inactive]:!hidden data-[hidden]:!hidden"
        >
          <SandpackLayout
            style={{
              height: "100%",
              width: "100%",
              border: "none",
              borderRadius: 0,
              background: "transparent",
              display: "flex",
              flex: 1,
              minHeight: 0,
            }}
          >
            <SandpackFileExplorer
              style={{
                height: "100%",
                width: "200px",
                minWidth: "200px",
                borderRight: "0.5px solid rgba(255,255,255,0.08)",
              }}
            />
            <div className="flex-1 h-full min-h-0 min-w-0">
              <SandpackCodeEditor
                style={{ height: "100%", width: "100%", flex: 1, minHeight: 0 }}
                showTabs
                showLineNumbers
                showInlineErrors
                closableTabs
                wrapContent
                initMode="immediate"
                readOnly
              />
            </div>
          </SandpackLayout>
        </TabsContent>

        <TabsContent
          value="console"
          keepMounted
          className="m-0 h-full w-full flex-1 flex flex-col min-h-0 [&[hidden]]:!hidden data-[state=inactive]:!hidden data-[hidden]:!hidden"
        >
          <SandpackLayout
            style={{
              height: "100%",
              width: "100%",
              border: "none",
              borderRadius: 0,
              background: "transparent",
              display: "flex",
              flex: 1,
              minHeight: 0,
            }}
          >
            <SandpackConsole
              style={{ height: "100%", width: "100%", flex: 1, minHeight: 0 }}
              showSyntaxError
              resetOnPreviewRestart
            />
          </SandpackLayout>
        </TabsContent>
      </div>

      {/* Preview error banner — uses onFixError (Gemini), not onImprove (Cline) */}
      {previewError &&
        !isGenerating &&
        !isImproving &&
        activeTab !== "code" && (
          <div className="absolute inset-x-0 -bottom-3 z-20 border-t border-red-500/20 bg-red-950/95 p-4 pb-6 backdrop-blur-md">
            <div className="flex items-center gap-2.5">
              <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-red-400/80" />
              <div className="min-w-0 flex-1">
                <p className="text-xs font-medium text-red-400">
                  Preview error
                </p>
                <p className="break-all text-[11px] text-red-300/60">
                  {previewError}
                </p>
              </div>
              <Button
                onClick={() => onFixError(previewError)}
                variant="destructive"
                size="sm"
                className="cursor-pointer font-medium"
              >
                <Bot className="h-3 w-3" />
                Fix with AI
              </Button>
              <button
                type="button"
                onClick={() => setPreviewError(null)}
                aria-label="Dismiss error"
                className="rounded-md p-1 text-red-300/60 hover:bg-red-900/50 hover:text-white transition-colors cursor-pointer"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>
        )}
    </Tabs>
  );
}

// ─── CodePanel (outer) ────────────────────────────────────────────────────────

export function CodePanel({
  fileData,
  isGenerating,
  statusLog,
  onImprove,
  onFixError,
  appTitle,
  isImproving,
  workspaceId,
  userId,
}: CodePanelProps) {
  const [activeTab, setActiveTab] = useState<ActiveTab>("preview");
  const [themeKey, setThemeKey] = useState<ThemeKey>("forgeDark");

  useEffect(() => {
    try {
      const saved = localStorage.getItem("forge_sandpack_theme") as ThemeKey | null;
      if (saved && AVAILABLE_THEMES[saved]) {
        setThemeKey(saved);
      }
    } catch {
      // LocalStorage might be inaccessible in private browsing or iframe
    }
  }, []);

  const handleThemeChange = (key: ThemeKey) => {
    setThemeKey(key);
    try {
      localStorage.setItem("forge_sandpack_theme", key);
    } catch {}
  };

  useEffect(() => {
    if (fileData) setActiveTab("preview");
  }, [fileData]);

  const files = fileData?.files ?? PLACEHOLDER_FILES;
  const dependencies = resolveAppDependencies(fileData);

  // Key only on file path set — NOT on file contents.
  // Content changes go through sandpack.updateFile() inside SandpackInner.
  // This prevents Sandpack from remounting when only code changes.
  const filePathKey = Object.keys(files).sort().join("|");

  return (
    <div className="flex flex-1 flex-col h-full min-h-0 w-full overflow-hidden">
      <SandpackProvider
        key={filePathKey}
        template="react"
        theme={AVAILABLE_THEMES[themeKey]?.theme ?? FORGE_DARK_THEME}
        files={files}
        customSetup={{ dependencies }}
        className="h-full w-full flex flex-1 flex-col min-h-0"
        style={{
          height: "100%",
          width: "100%",
          display: "flex",
          flexDirection: "column",
          flex: 1,
          minHeight: 0,
        }}
        options={{
          initMode: "immediate",
          autorun: true,
          bundlerTimeOut: 120000,
          externalResources: ["https://cdn.tailwindcss.com"],
          recompileMode: "delayed",
          recompileDelay: 500,
        }}
      >
        <SandpackInner
          isGenerating={isGenerating}
          statusLog={statusLog}
          activeTab={activeTab}
          setActiveTab={setActiveTab}
          themeKey={themeKey}
          onThemeChange={handleThemeChange}
          onImprove={onImprove}
          onFixError={onFixError}
          fileData={fileData}
          appTitle={appTitle}
          isImproving={isImproving}
          workspaceId={workspaceId}
          userId={userId}
        />
      </SandpackProvider>
    </div>
  );
}
